steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/test-service:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - gcr.io/$PROJECT_ID/test-service:$COMMIT_SHA

  - name: gcr.io/cloud-builders/kubectl
    id: set
    args:
      - set
      - image
      - deployment
      - test-service-deployment
      - test-service=gcr.io/$PROJECT_ID/test-service:$COMMIT_SHA
      - --namespace=$_KUBE_NAMESPACE
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-north1
      - CLOUDSDK_CONTAINER_CLUSTER=testing-cluster

substitutions:
  _KUBE_NAMESPACE: development
