apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: development
spec:
  limits:
    - default:
        memory: '256Mi'
        cpu: '200m'
      defaultRequest:
        memory: '128Mi'
        cpu: '100m'
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: staging
spec:
  limits:
    - default:
        memory: '256Mi'
        cpu: '200m'
      defaultRequest:
        memory: '128Mi'
        cpu: '100m'
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: production
spec:
  limits:
    - default:
        memory: '256Mi'
        cpu: '200m'
      defaultRequest:
        memory: '128Mi'
        cpu: '100m'
      type: Container
